package fwp.alsaccount.dao.refund;
// Generated Dec 20, 2016 4:04:41 PM by Hibernate Tools 5.2.0.Alpha3


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlsAppDispositionIdPk generated by hbm2java
 */
@Embeddable
public class AlsAppDispositionIdPk  implements java.io.Serializable {


     private String aaiAppIdentificationNo;
     private Integer aadSeqNo;

    public AlsAppDispositionIdPk() {
    }

    public AlsAppDispositionIdPk(String aaiAppIdentificationNo, Integer aadSeqNo) {
       this.aaiAppIdentificationNo = aaiAppIdentificationNo;
       this.aadSeqNo = aadSeqNo;
    }
   


    @Column(name="AAI_APP_IDENTIFICATION_NO", nullable=false, length=20)
    public String getAaiAppIdentificationNo() {
        return this.aaiAppIdentificationNo;
    }
    
    public void setAaiAppIdentificationNo(String aaiAppIdentificationNo) {
        this.aaiAppIdentificationNo = aaiAppIdentificationNo;
    }


    @Column(name="AAD_SEQ_NO", nullable=false, precision=6, scale=0)
    public Integer getAadSeqNo() {
        return this.aadSeqNo;
    }
    
    public void setAadSeqNo(Integer aadSeqNo) {
        this.aadSeqNo = aadSeqNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlsAppDispositionIdPk) ) return false;
		 AlsAppDispositionIdPk castOther = ( AlsAppDispositionIdPk ) other; 
         
		 return ( (this.getAaiAppIdentificationNo()==castOther.getAaiAppIdentificationNo()) || ( this.getAaiAppIdentificationNo()!=null && castOther.getAaiAppIdentificationNo()!=null && this.getAaiAppIdentificationNo().equals(castOther.getAaiAppIdentificationNo()) ) )
 && ( (this.getAadSeqNo()==castOther.getAadSeqNo()) || ( this.getAadSeqNo()!=null && castOther.getAadSeqNo()!=null && this.getAadSeqNo().equals(castOther.getAadSeqNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAaiAppIdentificationNo() == null ? 0 : this.getAaiAppIdentificationNo().hashCode() );
         result = 37 * result + ( getAadSeqNo() == null ? 0 : this.getAadSeqNo().hashCode() );
         return result;
   }   


}


