package fwp.alsaccount.dao.refund;
// Generated Dec 20, 2016 4:37:21 PM by Hibernate Tools 5.2.0.Alpha3


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlsPreappPersonDetails generated by hbm2java
 */
@Entity
@Table(name="ALS_PREAPP_PERSON_DETAILS"
    ,schema="ALS"
)
public class AlsPreappPersonDetails  implements java.io.Serializable {


     private AlsPreappPersonDetailsIdPk idPk;
     private Integer abiBatchNo;
     private Integer asiSubbatchNo;
     private Integer aptAppTypeCd;
     private String appdNewPerson;
     private Date appdPostmarkDt;
     private String appdHunterEdNo;
     private Date appdDob;
     private Integer appdAlsNo;
     private String appdSsn;
     private String appdEin;
     private String appdLastNm;
     private String appdFirstNm;
     private String appdMidInit;
     private String appdSuffix;
     private String appdResidencyInd;
     private Integer appdLenResidencyYrs;
     private Integer appdLenResidencyMo;
     private Date appdDtResDeclared;
     private Integer appdIdCd;
     private String appdFormOfIdNo;
     private String appdAddressInd;
     private String appdMailingAddress;
     private String appdMailingCity;
     private String appdMailingState;
     private String appdMailingZipCd;
     private String appdMailingCountry;
     private String appdHomePhone;
     private String appdWorkPhone;
     private String appdEmployerNm;
     private String appdSexCd;
     private Integer appdWeight;
     private Integer appdHeightFeet;
     private Integer appdHeightInches;
     private Integer appdEyeColorCd;
     private Integer appdHairColorCd;
     private String appdApplicationStatus;
     private Double appdApplicationAmt;
     private Date appdWhenLog;
     private String appdWhoLog;
     private String appdModiReason;
     private Double appdRefundAmt;
     private Double appdCurrentAmt;
     private String acCountyCd;
     private String appdMailingExclusion;
     private String appdContribHahInd;
     private Double appdContribHahAmount;

    public AlsPreappPersonDetails() {
    }

	
    public AlsPreappPersonDetails(AlsPreappPersonDetailsIdPk idPk, Integer abiBatchNo, Integer asiSubbatchNo, Integer aptAppTypeCd) {
        this.idPk = idPk;
        this.abiBatchNo = abiBatchNo;
        this.asiSubbatchNo = asiSubbatchNo;
        this.aptAppTypeCd = aptAppTypeCd;
    }
    public AlsPreappPersonDetails(AlsPreappPersonDetailsIdPk idPk, Integer abiBatchNo, Integer asiSubbatchNo, Integer aptAppTypeCd, String appdNewPerson, Date appdPostmarkDt, String appdHunterEdNo, Date appdDob, Integer appdAlsNo, String appdSsn, String appdEin, String appdLastNm, String appdFirstNm, String appdMidInit, String appdSuffix, String appdResidencyInd, Integer appdLenResidencyYrs, Integer appdLenResidencyMo, Date appdDtResDeclared, Integer appdIdCd, String appdFormOfIdNo, String appdAddressInd, String appdMailingAddress, String appdMailingCity, String appdMailingState, String appdMailingZipCd, String appdMailingCountry, String appdHomePhone, String appdWorkPhone, String appdEmployerNm, String appdSexCd, Integer appdWeight, Integer appdHeightFeet, Integer appdHeightInches, Integer appdEyeColorCd, Integer appdHairColorCd, String appdApplicationStatus, Double appdApplicationAmt, Date appdWhenLog, String appdWhoLog, String appdModiReason, Double appdRefundAmt, Double appdCurrentAmt, String acCountyCd, String appdMailingExclusion, String appdContribHahInd, Double appdContribHahAmount) {
       this.idPk = idPk;
       this.abiBatchNo = abiBatchNo;
       this.asiSubbatchNo = asiSubbatchNo;
       this.aptAppTypeCd = aptAppTypeCd;
       this.appdNewPerson = appdNewPerson;
       this.appdPostmarkDt = appdPostmarkDt;
       this.appdHunterEdNo = appdHunterEdNo;
       this.appdDob = appdDob;
       this.appdAlsNo = appdAlsNo;
       this.appdSsn = appdSsn;
       this.appdEin = appdEin;
       this.appdLastNm = appdLastNm;
       this.appdFirstNm = appdFirstNm;
       this.appdMidInit = appdMidInit;
       this.appdSuffix = appdSuffix;
       this.appdResidencyInd = appdResidencyInd;
       this.appdLenResidencyYrs = appdLenResidencyYrs;
       this.appdLenResidencyMo = appdLenResidencyMo;
       this.appdDtResDeclared = appdDtResDeclared;
       this.appdIdCd = appdIdCd;
       this.appdFormOfIdNo = appdFormOfIdNo;
       this.appdAddressInd = appdAddressInd;
       this.appdMailingAddress = appdMailingAddress;
       this.appdMailingCity = appdMailingCity;
       this.appdMailingState = appdMailingState;
       this.appdMailingZipCd = appdMailingZipCd;
       this.appdMailingCountry = appdMailingCountry;
       this.appdHomePhone = appdHomePhone;
       this.appdWorkPhone = appdWorkPhone;
       this.appdEmployerNm = appdEmployerNm;
       this.appdSexCd = appdSexCd;
       this.appdWeight = appdWeight;
       this.appdHeightFeet = appdHeightFeet;
       this.appdHeightInches = appdHeightInches;
       this.appdEyeColorCd = appdEyeColorCd;
       this.appdHairColorCd = appdHairColorCd;
       this.appdApplicationStatus = appdApplicationStatus;
       this.appdApplicationAmt = appdApplicationAmt;
       this.appdWhenLog = appdWhenLog;
       this.appdWhoLog = appdWhoLog;
       this.appdModiReason = appdModiReason;
       this.appdRefundAmt = appdRefundAmt;
       this.appdCurrentAmt = appdCurrentAmt;
       this.acCountyCd = acCountyCd;
       this.appdMailingExclusion = appdMailingExclusion;
       this.appdContribHahInd = appdContribHahInd;
       this.appdContribHahAmount = appdContribHahAmount;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="abiLicenseYr", column=@Column(name="ABI_LICENSE_YR", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="appdApplicationNo", column=@Column(name="APPD_APPLICATION_NO", nullable=false, length=14) ), 
        @AttributeOverride(name="apbiDataEntry", column=@Column(name="APBI_DATA_ENTRY", nullable=false, precision=1, scale=0) ) } )
    public AlsPreappPersonDetailsIdPk getIdPk() {
        return this.idPk;
    }
    
    public void setIdPk(AlsPreappPersonDetailsIdPk idPk) {
        this.idPk = idPk;
    }

    
    @Column(name="ABI_BATCH_NO", nullable=false, precision=7, scale=0)
    public Integer getAbiBatchNo() {
        return this.abiBatchNo;
    }
    
    public void setAbiBatchNo(Integer abiBatchNo) {
        this.abiBatchNo = abiBatchNo;
    }

    
    @Column(name="ASI_SUBBATCH_NO", nullable=false, precision=7, scale=0)
    public Integer getAsiSubbatchNo() {
        return this.asiSubbatchNo;
    }
    
    public void setAsiSubbatchNo(Integer asiSubbatchNo) {
        this.asiSubbatchNo = asiSubbatchNo;
    }

    
    @Column(name="APT_APP_TYPE_CD", nullable=false, precision=2, scale=0)
    public Integer getAptAppTypeCd() {
        return this.aptAppTypeCd;
    }
    
    public void setAptAppTypeCd(Integer aptAppTypeCd) {
        this.aptAppTypeCd = aptAppTypeCd;
    }

    
    @Column(name="APPD_NEW_PERSON", length=1)
    public String getAppdNewPerson() {
        return this.appdNewPerson;
    }
    
    public void setAppdNewPerson(String appdNewPerson) {
        this.appdNewPerson = appdNewPerson;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPD_POSTMARK_DT", length=7)
    public Date getAppdPostmarkDt() {
        return this.appdPostmarkDt;
    }
    
    public void setAppdPostmarkDt(Date appdPostmarkDt) {
        this.appdPostmarkDt = appdPostmarkDt;
    }

    
    @Column(name="APPD_HUNTER_ED_NO", length=7)
    public String getAppdHunterEdNo() {
        return this.appdHunterEdNo;
    }
    
    public void setAppdHunterEdNo(String appdHunterEdNo) {
        this.appdHunterEdNo = appdHunterEdNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPD_DOB", length=7)
    public Date getAppdDob() {
        return this.appdDob;
    }
    
    public void setAppdDob(Date appdDob) {
        this.appdDob = appdDob;
    }

    
    @Column(name="APPD_ALS_NO", precision=8, scale=0)
    public Integer getAppdAlsNo() {
        return this.appdAlsNo;
    }
    
    public void setAppdAlsNo(Integer appdAlsNo) {
        this.appdAlsNo = appdAlsNo;
    }

    
    @Column(name="APPD_SSN", length=9)
    public String getAppdSsn() {
        return this.appdSsn;
    }
    
    public void setAppdSsn(String appdSsn) {
        this.appdSsn = appdSsn;
    }

    
    @Column(name="APPD_EIN", length=9)
    public String getAppdEin() {
        return this.appdEin;
    }
    
    public void setAppdEin(String appdEin) {
        this.appdEin = appdEin;
    }

    
    @Column(name="APPD_LAST_NM", length=20)
    public String getAppdLastNm() {
        return this.appdLastNm;
    }
    
    public void setAppdLastNm(String appdLastNm) {
        this.appdLastNm = appdLastNm;
    }

    
    @Column(name="APPD_FIRST_NM", length=20)
    public String getAppdFirstNm() {
        return this.appdFirstNm;
    }
    
    public void setAppdFirstNm(String appdFirstNm) {
        this.appdFirstNm = appdFirstNm;
    }

    
    @Column(name="APPD_MID_INIT", length=1)
    public String getAppdMidInit() {
        return this.appdMidInit;
    }
    
    public void setAppdMidInit(String appdMidInit) {
        this.appdMidInit = appdMidInit;
    }

    
    @Column(name="APPD_SUFFIX", length=3)
    public String getAppdSuffix() {
        return this.appdSuffix;
    }
    
    public void setAppdSuffix(String appdSuffix) {
        this.appdSuffix = appdSuffix;
    }

    
    @Column(name="APPD_RESIDENCY_IND", length=1)
    public String getAppdResidencyInd() {
        return this.appdResidencyInd;
    }
    
    public void setAppdResidencyInd(String appdResidencyInd) {
        this.appdResidencyInd = appdResidencyInd;
    }

    
    @Column(name="APPD_LEN_RESIDENCY_YRS", precision=3, scale=0)
    public Integer getAppdLenResidencyYrs() {
        return this.appdLenResidencyYrs;
    }
    
    public void setAppdLenResidencyYrs(Integer appdLenResidencyYrs) {
        this.appdLenResidencyYrs = appdLenResidencyYrs;
    }

    
    @Column(name="APPD_LEN_RESIDENCY_MO", precision=2, scale=0)
    public Integer getAppdLenResidencyMo() {
        return this.appdLenResidencyMo;
    }
    
    public void setAppdLenResidencyMo(Integer appdLenResidencyMo) {
        this.appdLenResidencyMo = appdLenResidencyMo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPD_DT_RES_DECLARED", length=7)
    public Date getAppdDtResDeclared() {
        return this.appdDtResDeclared;
    }
    
    public void setAppdDtResDeclared(Date appdDtResDeclared) {
        this.appdDtResDeclared = appdDtResDeclared;
    }

    
    @Column(name="APPD_ID_CD", precision=4, scale=0)
    public Integer getAppdIdCd() {
        return this.appdIdCd;
    }
    
    public void setAppdIdCd(Integer appdIdCd) {
        this.appdIdCd = appdIdCd;
    }

    
    @Column(name="APPD_FORM_OF_ID_NO", length=20)
    public String getAppdFormOfIdNo() {
        return this.appdFormOfIdNo;
    }
    
    public void setAppdFormOfIdNo(String appdFormOfIdNo) {
        this.appdFormOfIdNo = appdFormOfIdNo;
    }

    
    @Column(name="APPD_ADDRESS_IND", length=1)
    public String getAppdAddressInd() {
        return this.appdAddressInd;
    }
    
    public void setAppdAddressInd(String appdAddressInd) {
        this.appdAddressInd = appdAddressInd;
    }

    
    @Column(name="APPD_MAILING_ADDRESS", length=30)
    public String getAppdMailingAddress() {
        return this.appdMailingAddress;
    }
    
    public void setAppdMailingAddress(String appdMailingAddress) {
        this.appdMailingAddress = appdMailingAddress;
    }

    
    @Column(name="APPD_MAILING_CITY", length=30)
    public String getAppdMailingCity() {
        return this.appdMailingCity;
    }
    
    public void setAppdMailingCity(String appdMailingCity) {
        this.appdMailingCity = appdMailingCity;
    }

    
    @Column(name="APPD_MAILING_STATE", length=2)
    public String getAppdMailingState() {
        return this.appdMailingState;
    }
    
    public void setAppdMailingState(String appdMailingState) {
        this.appdMailingState = appdMailingState;
    }

    
    @Column(name="APPD_MAILING_ZIP_CD", length=10)
    public String getAppdMailingZipCd() {
        return this.appdMailingZipCd;
    }
    
    public void setAppdMailingZipCd(String appdMailingZipCd) {
        this.appdMailingZipCd = appdMailingZipCd;
    }

    
    @Column(name="APPD_MAILING_COUNTRY", length=3)
    public String getAppdMailingCountry() {
        return this.appdMailingCountry;
    }
    
    public void setAppdMailingCountry(String appdMailingCountry) {
        this.appdMailingCountry = appdMailingCountry;
    }

    
    @Column(name="APPD_HOME_PHONE", length=14)
    public String getAppdHomePhone() {
        return this.appdHomePhone;
    }
    
    public void setAppdHomePhone(String appdHomePhone) {
        this.appdHomePhone = appdHomePhone;
    }

    
    @Column(name="APPD_WORK_PHONE", length=14)
    public String getAppdWorkPhone() {
        return this.appdWorkPhone;
    }
    
    public void setAppdWorkPhone(String appdWorkPhone) {
        this.appdWorkPhone = appdWorkPhone;
    }

    
    @Column(name="APPD_EMPLOYER_NM", length=40)
    public String getAppdEmployerNm() {
        return this.appdEmployerNm;
    }
    
    public void setAppdEmployerNm(String appdEmployerNm) {
        this.appdEmployerNm = appdEmployerNm;
    }

    
    @Column(name="APPD_SEX_CD", length=1)
    public String getAppdSexCd() {
        return this.appdSexCd;
    }
    
    public void setAppdSexCd(String appdSexCd) {
        this.appdSexCd = appdSexCd;
    }

    
    @Column(name="APPD_WEIGHT", precision=3, scale=0)
    public Integer getAppdWeight() {
        return this.appdWeight;
    }
    
    public void setAppdWeight(Integer appdWeight) {
        this.appdWeight = appdWeight;
    }

    
    @Column(name="APPD_HEIGHT_FEET", precision=2, scale=0)
    public Integer getAppdHeightFeet() {
        return this.appdHeightFeet;
    }
    
    public void setAppdHeightFeet(Integer appdHeightFeet) {
        this.appdHeightFeet = appdHeightFeet;
    }

    
    @Column(name="APPD_HEIGHT_INCHES", precision=2, scale=0)
    public Integer getAppdHeightInches() {
        return this.appdHeightInches;
    }
    
    public void setAppdHeightInches(Integer appdHeightInches) {
        this.appdHeightInches = appdHeightInches;
    }

    
    @Column(name="APPD_EYE_COLOR_CD", precision=2, scale=0)
    public Integer getAppdEyeColorCd() {
        return this.appdEyeColorCd;
    }
    
    public void setAppdEyeColorCd(Integer appdEyeColorCd) {
        this.appdEyeColorCd = appdEyeColorCd;
    }

    
    @Column(name="APPD_HAIR_COLOR_CD", precision=2, scale=0)
    public Integer getAppdHairColorCd() {
        return this.appdHairColorCd;
    }
    
    public void setAppdHairColorCd(Integer appdHairColorCd) {
        this.appdHairColorCd = appdHairColorCd;
    }

    
    @Column(name="APPD_APPLICATION_STATUS", length=1)
    public String getAppdApplicationStatus() {
        return this.appdApplicationStatus;
    }
    
    public void setAppdApplicationStatus(String appdApplicationStatus) {
        this.appdApplicationStatus = appdApplicationStatus;
    }

    
    @Column(name="APPD_APPLICATION_AMT", precision=8)
    public Double getAppdApplicationAmt() {
        return this.appdApplicationAmt;
    }
    
    public void setAppdApplicationAmt(Double appdApplicationAmt) {
        this.appdApplicationAmt = appdApplicationAmt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APPD_WHEN_LOG", length=7)
    public Date getAppdWhenLog() {
        return this.appdWhenLog;
    }
    
    public void setAppdWhenLog(Date appdWhenLog) {
        this.appdWhenLog = appdWhenLog;
    }

    
    @Column(name="APPD_WHO_LOG", length=15)
    public String getAppdWhoLog() {
        return this.appdWhoLog;
    }
    
    public void setAppdWhoLog(String appdWhoLog) {
        this.appdWhoLog = appdWhoLog;
    }

    
    @Column(name="APPD_MODI_REASON", length=200)
    public String getAppdModiReason() {
        return this.appdModiReason;
    }
    
    public void setAppdModiReason(String appdModiReason) {
        this.appdModiReason = appdModiReason;
    }

    
    @Column(name="APPD_REFUND_AMT", precision=8)
    public Double getAppdRefundAmt() {
        return this.appdRefundAmt;
    }
    
    public void setAppdRefundAmt(Double appdRefundAmt) {
        this.appdRefundAmt = appdRefundAmt;
    }

    
    @Column(name="APPD_CURRENT_AMT", precision=8)
    public Double getAppdCurrentAmt() {
        return this.appdCurrentAmt;
    }
    
    public void setAppdCurrentAmt(Double appdCurrentAmt) {
        this.appdCurrentAmt = appdCurrentAmt;
    }

    
    @Column(name="AC_COUNTY_CD", length=3)
    public String getAcCountyCd() {
        return this.acCountyCd;
    }
    
    public void setAcCountyCd(String acCountyCd) {
        this.acCountyCd = acCountyCd;
    }

    
    @Column(name="APPD_MAILING_EXCLUSION", length=1)
    public String getAppdMailingExclusion() {
        return this.appdMailingExclusion;
    }
    
    public void setAppdMailingExclusion(String appdMailingExclusion) {
        this.appdMailingExclusion = appdMailingExclusion;
    }

    
    @Column(name="APPD_CONTRIB_HAH_IND", length=1)
    public String getAppdContribHahInd() {
        return this.appdContribHahInd;
    }
    
    public void setAppdContribHahInd(String appdContribHahInd) {
        this.appdContribHahInd = appdContribHahInd;
    }

    
    @Column(name="APPD_CONTRIB_HAH_AMOUNT", precision=8)
    public Double getAppdContribHahAmount() {
        return this.appdContribHahAmount;
    }
    
    public void setAppdContribHahAmount(Double appdContribHahAmount) {
        this.appdContribHahAmount = appdContribHahAmount;
    }




}


