package fwp.alsaccount.dao.refund;
// Generated Dec 20, 2016 4:37:21 PM by Hibernate Tools 5.2.0.Alpha3


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlsPreappPersonDetailsIdPk generated by hbm2java
 */
@Embeddable
public class AlsPreappPersonDetailsIdPk  implements java.io.Serializable {


     private Integer abiLicenseYr;
     private String appdApplicationNo;
     private Integer apbiDataEntry;

    public AlsPreappPersonDetailsIdPk() {
    }

    public AlsPreappPersonDetailsIdPk(Integer abiLicenseYr, String appdApplicationNo, Integer apbiDataEntry) {
       this.abiLicenseYr = abiLicenseYr;
       this.appdApplicationNo = appdApplicationNo;
       this.apbiDataEntry = apbiDataEntry;
    }
   


    @Column(name="ABI_LICENSE_YR", nullable=false, precision=4, scale=0)
    public Integer getAbiLicenseYr() {
        return this.abiLicenseYr;
    }
    
    public void setAbiLicenseYr(Integer abiLicenseYr) {
        this.abiLicenseYr = abiLicenseYr;
    }


    @Column(name="APPD_APPLICATION_NO", nullable=false, length=14)
    public String getAppdApplicationNo() {
        return this.appdApplicationNo;
    }
    
    public void setAppdApplicationNo(String appdApplicationNo) {
        this.appdApplicationNo = appdApplicationNo;
    }


    @Column(name="APBI_DATA_ENTRY", nullable=false, precision=1, scale=0)
    public Integer getApbiDataEntry() {
        return this.apbiDataEntry;
    }
    
    public void setApbiDataEntry(Integer apbiDataEntry) {
        this.apbiDataEntry = apbiDataEntry;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlsPreappPersonDetailsIdPk) ) return false;
		 AlsPreappPersonDetailsIdPk castOther = ( AlsPreappPersonDetailsIdPk ) other; 
         
		 return ( (this.getAbiLicenseYr()==castOther.getAbiLicenseYr()) || ( this.getAbiLicenseYr()!=null && castOther.getAbiLicenseYr()!=null && this.getAbiLicenseYr().equals(castOther.getAbiLicenseYr()) ) )
 && ( (this.getAppdApplicationNo()==castOther.getAppdApplicationNo()) || ( this.getAppdApplicationNo()!=null && castOther.getAppdApplicationNo()!=null && this.getAppdApplicationNo().equals(castOther.getAppdApplicationNo()) ) )
 && ( (this.getApbiDataEntry()==castOther.getApbiDataEntry()) || ( this.getApbiDataEntry()!=null && castOther.getApbiDataEntry()!=null && this.getApbiDataEntry().equals(castOther.getApbiDataEntry()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAbiLicenseYr() == null ? 0 : this.getAbiLicenseYr().hashCode() );
         result = 37 * result + ( getAppdApplicationNo() == null ? 0 : this.getAppdApplicationNo().hashCode() );
         result = 37 * result + ( getApbiDataEntry() == null ? 0 : this.getApbiDataEntry().hashCode() );
         return result;
   }   


}


