package fwp.alsaccount.dao.refund;
// Generated Dec 15, 2016 1:48:57 PM by Hibernate Tools 5.2.0.Alpha3


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlsPersonItemTemplLinkIdPk generated by hbm2java
 */
@Embeddable
public class AlsPersonItemTemplLinkIdPk  implements java.io.Serializable {


     private Integer aptAppTypeCd;
     private Integer aptDataEntry;
     private String apitlItemTypeCd;

    public AlsPersonItemTemplLinkIdPk() {
    }

    public AlsPersonItemTemplLinkIdPk(Integer aptAppTypeCd, Integer aptDataEntry, String apitlItemTypeCd) {
       this.aptAppTypeCd = aptAppTypeCd;
       this.aptDataEntry = aptDataEntry;
       this.apitlItemTypeCd = apitlItemTypeCd;
    }
   


    @Column(name="APT_APP_TYPE_CD", nullable=false, precision=2, scale=0)
    public Integer getAptAppTypeCd() {
        return this.aptAppTypeCd;
    }
    
    public void setAptAppTypeCd(Integer aptAppTypeCd) {
        this.aptAppTypeCd = aptAppTypeCd;
    }


    @Column(name="APT_DATA_ENTRY", nullable=false, precision=1, scale=0)
    public Integer getAptDataEntry() {
        return this.aptDataEntry;
    }
    
    public void setAptDataEntry(Integer aptDataEntry) {
        this.aptDataEntry = aptDataEntry;
    }


    @Column(name="APITL_ITEM_TYPE_CD", nullable=false, length=7)
    public String getApitlItemTypeCd() {
        return this.apitlItemTypeCd;
    }
    
    public void setApitlItemTypeCd(String apitlItemTypeCd) {
        this.apitlItemTypeCd = apitlItemTypeCd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlsPersonItemTemplLinkIdPk) ) return false;
		 AlsPersonItemTemplLinkIdPk castOther = ( AlsPersonItemTemplLinkIdPk ) other; 
         
		 return ( (this.getAptAppTypeCd()==castOther.getAptAppTypeCd()) || ( this.getAptAppTypeCd()!=null && castOther.getAptAppTypeCd()!=null && this.getAptAppTypeCd().equals(castOther.getAptAppTypeCd()) ) )
 && ( (this.getAptDataEntry()==castOther.getAptDataEntry()) || ( this.getAptDataEntry()!=null && castOther.getAptDataEntry()!=null && this.getAptDataEntry().equals(castOther.getAptDataEntry()) ) )
 && ( (this.getApitlItemTypeCd()==castOther.getApitlItemTypeCd()) || ( this.getApitlItemTypeCd()!=null && castOther.getApitlItemTypeCd()!=null && this.getApitlItemTypeCd().equals(castOther.getApitlItemTypeCd()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAptAppTypeCd() == null ? 0 : this.getAptAppTypeCd().hashCode() );
         result = 37 * result + ( getAptDataEntry() == null ? 0 : this.getAptDataEntry().hashCode() );
         result = 37 * result + ( getApitlItemTypeCd() == null ? 0 : this.getApitlItemTypeCd().hashCode() );
         return result;
   }   


}


