package fwp.alsaccount.dao.refund;
// Generated Dec 15, 2016 1:48:57 PM by Hibernate Tools 5.2.0.Alpha3


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlsPersonItemTemplLink generated by hbm2java
 */
@Entity
@Table(name="ALS_PERSON_ITEM_TEMPL_LINK"
    ,schema="ALS"
)
public class AlsPersonItemTemplLink  implements java.io.Serializable {


     private AlsPersonItemTemplLinkIdPk idPk;
     private Integer aitmItemTemplateCd;
     private Date apitlWhenLog;
     private String apitlWhoLog;

    public AlsPersonItemTemplLink() {
    }

    public AlsPersonItemTemplLink(AlsPersonItemTemplLinkIdPk idPk, Integer aitmItemTemplateCd, Date apitlWhenLog, String apitlWhoLog) {
       this.idPk = idPk;
       this.aitmItemTemplateCd = aitmItemTemplateCd;
       this.apitlWhenLog = apitlWhenLog;
       this.apitlWhoLog = apitlWhoLog;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="aptAppTypeCd", column=@Column(name="APT_APP_TYPE_CD", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="aptDataEntry", column=@Column(name="APT_DATA_ENTRY", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="apitlItemTypeCd", column=@Column(name="APITL_ITEM_TYPE_CD", nullable=false, length=7) ) } )
    public AlsPersonItemTemplLinkIdPk getIdPk() {
        return this.idPk;
    }
    
    public void setIdPk(AlsPersonItemTemplLinkIdPk idPk) {
        this.idPk = idPk;
    }

    
    @Column(name="AITM_ITEM_TEMPLATE_CD", nullable=false, precision=2, scale=0)
    public Integer getAitmItemTemplateCd() {
        return this.aitmItemTemplateCd;
    }
    
    public void setAitmItemTemplateCd(Integer aitmItemTemplateCd) {
        this.aitmItemTemplateCd = aitmItemTemplateCd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="APITL_WHEN_LOG", nullable=false, length=7)
    public Date getApitlWhenLog() {
        return this.apitlWhenLog;
    }
    
    public void setApitlWhenLog(Date apitlWhenLog) {
        this.apitlWhenLog = apitlWhenLog;
    }

    
    @Column(name="APITL_WHO_LOG", nullable=false, length=15)
    public String getApitlWhoLog() {
        return this.apitlWhoLog;
    }
    
    public void setApitlWhoLog(String apitlWhoLog) {
        this.apitlWhoLog = apitlWhoLog;
    }




}


